### ISSUE TITLE
SpringSocialSecurityDemoWebappConfig has multiple PostConstruct methods

### ISSUE THREAD

**Issue by chrylis** [socialsignin/spring-social-security-demo#5]
The `@Configuration` class annotates multiple methods with [`@PostConstruct`](http://docs.oracle.com/javaee/7/api/javax/annotation/PostConstruct.html), but the annotation's spec requires a maximum of one annotated method. The example may work because one method is a no-op, but this behavior is unspecified.

**Comment by michaellavelle** [comment]
Thank you chrylis - the @PostConstruct method in question is implemented in SocialConfig and should have been removed from SpringSocialSecurityDemoWebappConfig - I've now removed this duplicate method. - Cheers,  Michael
